[package]
name = "todos"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
anyhow = "1"
strum = { version = "*", features = ["derive"] }
strum_macros = "0.27.2"
home = "*"
